version: "3"
services:
  gatewayservice:
    image: registry.digitalocean.com/rsoi-project/gatewayservice
    build:
      context: ./Gatewayservice
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app/Gatewayservice
  paymentservice:
    image: registry.digitalocean.com/rsoi-project/paymentservice
    build:
      context: ./PaymentService
    restart: always
    ports:
      - "8060:8060"
    volumes:
      - .:/app/PaymentService
  loyaltyservice:
    image: registry.digitalocean.com/rsoi-project/loyaltyservice
    build:
      context: ./LoyaltyService
    restart: always
    ports:
      - "8050:8050"
    volumes:
      - .:/app/LoyaltyService
  reservationservice:
    image: registry.digitalocean.com/rsoi-project/reservationservice
    build:
      context: ./ReservationService
    restart: always
    ports:
      - "8070:8070"
    volumes:
      - .:/app/ReservationService
  sessionservice:
    image: registry.digitalocean.com/rsoi-project/sessionservice
    build:
      context: ./Session_Service
    restart: always
    ports:
      - "8040:8040"
    volumes:
      - .:/app/Session_Service
  reportservice:
    image: registry.digitalocean.com/rsoi-project/reportservice
    build:
      context: ./Report_Service
    restart: always
    ports:
      - "8030:8030"
    volumes:
      - .:/app/Report_Service
