# Generated by Django 4.1.2 on 2023-04-18 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelUid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('stars', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationUid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('paymentUid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('hotel_uid', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(max_length=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
    ]
