loyalty:
  service:
    port: 8050
    image:
      name: abdiaoo/loyaltyservice
      version: "latest"
    database:
      name: loyalties
payment:
  service:
    port: 8060
    image:
      name: abdiaoo/paymentservice
      version: "latest"
    database:
      name: payments
reservation:
  service:
    port: 8070
    image:
      name: abdiaoo/reservationservice
      version: "latest"
    database:
      name: reservations
session:
  service:
    port: 8040
    image:
      name: abdiaoo/sessionservice
      version: "latest"
    database:
      name: session
reports:
  service:
    port: 8030
    image:
      name: abdiaoo/reportservice
      version: "latest"
    database:
      name: reports
gateway:
  service:
    port: 8080
    image:
      name: abdiaoo/gatewayservice
      version: "latest"
    isGateway: true
