name: Build Project
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
env:
  DOCKERHUB_USERNAME: abdiaoo
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v2
      - name: Build Images
        run: docker compose build
      - name: Voir les images
        run: docker images
      - name: Login to Docker Hub
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - name: Push Payment image in to DockerHub
        run: docker push abdiaoo/paymentservice:latest
      - name: Push Loyalty image in to DockerHub
        run: docker push abdiaoo/loyaltyservice:latest
      - name: Push Session image in to DockerHub
        run: docker push abdiaoo/sessionservice:latest
      - name: Push Report image in to DockerHub
        run: docker push abdiaoo/reportservice:latest
      - name: Push Reservation image in to DockerHub
        run: docker push abdiaoo/reservationservice:latest
      - name: Push Gateway image in to DockerHub
        run: docker push abdiaoo/gatewayservice:latest
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: k8s cluster kubeconfig
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 1200 rsoi-cluster-project
      - name: Deployment to the cluster
        run: |
          cd k8s
          helm upgrade --install postgres postgres-chart/
          helm upgrade --install services services-chart/
          kubectl apply -f load-Balancer.yaml
          sleep 120
